# Generated by Django 4.0.6 on 2022-07-28 15:03

import commons.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_id', models.CharField(default=commons.db.models.random_ref_id, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.IntegerField(default=0)),
                ('user_id', models.CharField(max_length=255)),
                ('portfolio_id', models.CharField(max_length=255)),
                ('trade_type', models.PositiveSmallIntegerField()),
                ('security_type', models.CharField(max_length=255)),
                ('ticker', models.CharField(max_length=255)),
                ('volume', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=65)),
                ('status', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'trade',
                'ordering': ('-id',),
            },
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['user_id', 'portfolio_id', 'ticker', 'trade_type', 'status', 'is_deleted'], name='trade_user_id_355f71_idx'),
        ),
    ]
